services:
  postgres:
    image: postgres:16-alpine # Lekka wersja najnowszego stabilnego Postgresa
    container_name: nexo-postgres
    network_mode: bridge
    ports:
      - "5433:5432" # Mapowanie portu: zewnetrzny(Twój komputer) : wewnetrzny(wewnatrz Dockera)
    environment:
      POSTGRES_DB: nexo_db
      POSTGRES_USER: nexo_user
      POSTGRES_PASSWORD: nexo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data # Dzięki temu dane nie znikną po restarcie Dockera

volumes:
  postgres_data: