services:
  postgres:
    image: postgres:16-alpine
    container_name: nexo-postgres
    network_mode: bridge
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: nexo_db
      POSTGRES_USER: nexo_user
      POSTGRES_PASSWORD: nexo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: