name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Get repo code
      uses: actions/checkout@v4

    - name: Test maven project
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: 'maven'

    - name: Run unit tests
      run: ./mvnw test

  build-and-push:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo code
        uses: actions/checkout@v4

      - name: Log to azure ACR(container registry)
        uses: azure/docker-login@v1
        with:
          login-server: nexoregistryheczko.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build docker image
        run: |
          docker build -t nexoregistryheczko.azurecr.io/backend-nexo:latest .
          docker push nexoregistryheczko.azurecr.io/backend-nexo:latest